### ISSUE TITLE
Home page: The revolution slider changed

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#10]
The revolution slider and title bar was setup exactly as needed, full width slider, no space below title bar. Now it is a small slider with large space margins. I spent a lot of time getting that to display correctly and now my work is gone. This should not have been changed and needs to be put back the way it was. See screenshot here of how it was and should be: https://drive.google.com/file/d/0B8YmuQMr98J_VVFCc1owbmFxYmM/view?usp=sharing

**Comment by le-darshan** [comment]
now the home page slider is full width i have reverted my css. actually i don't know that my css was conflicting to slider otherwise i will revert it earlier. now its fixed.
