### ISSUE TITLE
Project photos on wrong admin tab

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#100]
Why do we have project images below the details and also on the project images tab above?
The project images section should be only on the images tab above not listed below the project details.
![image](https://cloud.githubusercontent.com/assets/9610332/6329750/2dbf0512-bb41-11e4-9bee-239ce74c6d2c.png)

**Comment by le-darshan** [comment]
ok small typo error was there. now fixed.

**Comment by Mark-Jefferson** [comment]
Good job, thanks
