### ISSUE TITLE
Still getting Leave this page? pop on frontend searches

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#102]
I can use the search box one time, but if I do more searches I get the popup of Leave this page? That should not popup.
![image](https://cloud.githubusercontent.com/assets/9610332/6330140/ec2870f4-bb43-11e4-87a0-ff2b37d6da6d.png)

**Comment by le-darshan** [comment]
this issue is fixed. but before testing it first can you clear all browsing data and history then test it.
