### ISSUE TITLE
Some includes are hard coded to /dev/ directory

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#104]
Some includes are showing an error message because they reference /dev/ directory after dev is deleted. See screenshot.
![image](https://cloud.githubusercontent.com/assets/9610332/6363205/ab0de0d8-bc63-11e4-94bd-e4bd05031fcd.png)

**Comment by le-darshan** [comment]
this warning issues are fixed now.
