### ISSUE TITLE
Client reported did not receive registration confirmation email

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#105]
The client has said they did not receive an email when they registered. I can not test it though until the hard coded /dev1/ issue is fixed, it looks like registration is not working now until that is fixed.

After you fix the dev1 path issue. please do a test registration and check if you receive an email confirmation.

**Comment by le-darshan** [comment]
dev1 issue is fixed, and i tested with registering new user. and i recived an approval mail.
![mail](https://cloud.githubusercontent.com/assets/5223025/6368877/c32b896a-bd06-11e4-9f37-fa1f7a637bd2.png)
