### ISSUE TITLE
Home page: Margins are broken

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#11]
The margins on the home page still need to be returned to normal on the left and right. The width of the content area is fine but there should be some space between the text and the side of content area. See this screenshot for normal left right margins: https://drive.google.com/file/d/0B8YmuQMr98J_VVFCc1owbmFxYmM/view?usp=sharing

**Comment by le-darshan** [comment]
can you check this point i have put some margin in home page.
