### ISSUE TITLE
Email Photo: Email FROM address change

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#14]
Emails sent from the photos module should be sent from noreply@wedwishes.com

**Comment by le-darshan** [comment]
the from address is changed

**Comment by Mark-Jefferson** [comment]
The email has some text on the link in the body that needs to change. 
Punit Kukadia has shared the photo with you. 

Please correct the username so that it is using the correct username.

**Comment by le-darshan** [comment]
username is corrected now it will show the sender's username now
