### ISSUE TITLE
Professional Profile page articles

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#18]
On the professional profile page there is a tab for articles. This is currently showing Forum posts, but it should list blog articles written by that pro, not forum posts.

**Comment by le-darshan** [comment]
i am not getting your point which blog articles? can you give one example of it.

**Comment by Mark-Jefferson** [comment]
Check the specs. Professionals should have the ability to write Posts (blog articles) and submit them as content contributors. The site administrator will approve them before publishing them. This is a sample Post (blog article) http://wedwishes.com/dev1/uncategorized/hello-world/

**Comment by le-darshan** [comment]
i have set post article in the article tab.
