### ISSUE TITLE
Subscriber registration: need password confirm

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#21]
Need to add a second 'confirm password' field

**Comment by le-darshan** [comment]
confirm password field is added for subscriber registration

**Comment by Mark-Jefferson** [comment]
?? The system is generating a password, do we need password input??

**Comment by le-darshan** [comment]
thats the exactly i was thinking we dont need password field at registration time because we are generating random password for user.

**Comment by Mark-Jefferson** [comment]
ok remove it, thanks

**Comment by Mark-Jefferson** [comment]
Please make sure you don't work on the issues assigned to me. I will do those.

**Comment by le-darshan** [comment]
password fields are removed from subscriber registration
