### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#25]
Replace WP logo with WedWishes logo
Need link to registration page
Facebook button does not work
Lower Register link should link to registration page
Screenshot: https://drive.google.com/open?id=0B8YmuQMr98J_em5KOW9TamFtQVU&authuser=0

Can we make our Login page more like this one?
https://www.houzz.com/signin/u=aHR0cDovL3d3dy5ob3V6ei5jb20v/d=web/s=aG9tZQ%3D%3D

**Comment by le-darshan** [comment]
can you provide permission for punit@logicexpress.in email to view the photos on google drive.

**Comment by Mark-Jefferson** [comment]
this has now been shared

**Comment by le-darshan** [comment]
login page changes are done now can you test it
