### ISSUE TITLE
User Login flow for Your WedWishes link

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#27]
I registered as a new user and logged in and was directed to the home page, and have no link to get to their profile administration page. 
Lets change the Log In process and flow.

When logged out, the Your WedWishes link on the navigation should direct to a page like 
https://www.houzz.com/signin/u=aHR0cDovL3d3dy5ob3V6ei5jb20v/d=web/s=aG9tZQ%3D%3D

When logged in, the Your WedWishes link on the navigation should direct to the user profile dashboard where they have their Favorite photos, link to edit profile, etc...

**Comment by le-darshan** [comment]
i have set the signin and registration as explained can you check the process.
