### ISSUE TITLE
Discussion user photo issue

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#31]
Make user photo on front of Discussions module to be max-width and max-height 120px

**Comment by Mark-Jefferson** [comment]
screenshot
https://drive.google.com/file/d/0B8YmuQMr98J_aF9oQWJ6bGhhT1k/view?usp=sharing

**Comment by le-darshan** [comment]
user photo max-width and max-height is set now to 120px

**Comment by Mark-Jefferson** [comment]
I can't test this yet until I can upload a user photo. Still getting error
