### ISSUE TITLE
Registration Display Name and Style

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#34]
When I filled out the form on this page
http://wedwishes.com/dev1/subscriber-registration/
It told me the user name was already in use and the 2 fields Display Name and Style did not keep the information I entered, but all the other fields did.
Lets keep all of the information entered so it does not need to be re-entered.

**Comment by le-darshan** [comment]
now all the fields are holding the values can you test it
