### ISSUE TITLE
Favorite Books

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#35]
1. Remove or make hidden "Thank you for creating with WordPress. Version 4.0.1" at the bottom
2. I saved a photo without creating a Favorite Book. Can we set a default book name such as "Ideas Book 1" ?
3. I created a new book category called Tuxedo Ideas and saved a photo in it. Then I went to another photo to save it and the Tuxedo Ideas was not in my drop list of Select Your Favorites in the popup. I had to navigate away to another page, then come back to the photos page, and then it populated. It could be related to the fix of not refreshing or reloading the page after saving the photo.

**Comment by le-darshan** [comment]
the issues regarding the favorites is fixed can you test it
