### ISSUE TITLE
Favorites Detail Popup

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#36]
Do we need to limit the size if the pics in detail view of popup window? This popup window is larger than the screen and difficult to close it.

Screenshot https://drive.google.com/file/d/0B8YmuQMr98J_ck5vbHZrQU5qWTQ/view?usp=sharing

**Comment by le-darshan** [comment]
i have set image width to 50% now it will not get larger then screen size

**Comment by Mark-Jefferson** [comment]
We need to set it to max-height:75% or something similar because the image is still too tall in the popup.

**Comment by le-darshan** [comment]
i have set max-height to 650px can you check now
