### ISSUE TITLE
Favorites Navigation

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#37]
When in the Favorites section I can see the books I have created but when I click on a book, there is no title on that book page so I don't know what book or folder I am currently in.
Also there is no way to get back to the previous page or folder so I can see all books again.

Lets add the book title to the top of each book page, and add a link at the top and the bottom "Back To All Favorites"

**Comment by le-darshan** [comment]
title of favorite book is showing now and back to all link is also set
