### ISSUE TITLE
Professional Registration 2

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#40]
This registration is giving a lot of errors including
Fatal error: Class 'Photos' not found in /home/w3d53r/public_html/dev1/wp-content/plugins/photos-browser/photobrowser.php on line 18

Can you please fix and test this registration very thoroughly.
Services provided
Areas Served
Nearest Major city
Should all allow multiple input separated by comma such as Atlanta, New York, Los Angeles, San Diego

**Comment by le-darshan** [comment]
errors are removed now and the validations which are restricting to enter comma seperated values of specified fields are removed now.
