### ISSUE TITLE
Professional Registration Alert message

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#47]
When I click Register on the professional registration form, it creates a popup alert message "Confirm Navigation, You have unsaved changes. Proceed anyway? Are you sure you want to leave this page?"

See screenshot  https://drive.google.com/file/d/0B8YmuQMr98J_ZWMteTVxMmNiQUU/view?usp=sharing

**Comment by le-darshan** [comment]
the alert box is removed now.
