### ISSUE TITLE
Professional Registration Edits

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#48]
See screen shots for edits needed on Professional registration form
https://drive.google.com/file/d/0B8YmuQMr98J_cnJ3c1hUZ0h4Y28/view?usp=sharing
1. Remove LC from Emaillc
2. Remove password field since it is auto generated
3. Remove business name from Full name or business name since we have Business further below

**Comment by le-darshan** [comment]
all changes are done in this point can you test it
