### ISSUE TITLE
Favorites issue 1

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#51]
When saving photos as favorites, if I do not change the "Create new" drop menu to a previously created book, the system creates multiple books with the same name. 
So if i Save as favorite and change nothing so that it says, Create New and Ideas Book 1, and do this for everything I save, it will create multiple books with the same name and only one image in each book.
https://drive.google.com/file/d/0B8YmuQMr98J_RTROU3NBNWRXM3c/view?usp=sharing

We need to check the book name to see if that book is already created, and that will force the user to either select the book from the drop list or create a book with a different name. Sound good?

**Comment by le-darshan** [comment]
this issue is fixed i have put a check on book name if the book name is found then it will redirect user again to the form with message.

**Comment by Mark-Jefferson** [comment]
It looks like we are checking against all books on all users. I could not create a book name that was not created on my account but was already created on a different account. Lets check only within the account for duplicate book names.

**Comment by le-darshan** [comment]
this is issue is fixed now can you test it
