### ISSUE TITLE
Browse photos test description

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#53]
I uploaded photos with descriptions but always see only "this is the test description" displayed on the browse photos section.

On the popup of the photos only the URL information is showing from the info I entered. Please make the edits listed on this screenshot:
https://drive.google.com/file/d/0B8YmuQMr98J_SzRNdnEza3BvbWc/view?usp=sharing

**Comment by le-darshan** [comment]
the changes are done for this point now.
