### ISSUE TITLE
Project Manager User List Not complete

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#54]
When I login as Admin and go to Project Manager, the Select User list is not showing all professional accounts or pro users that have uploaded projects. Only a few are showing and it is also showing white spaces gaps in the drop list of users.

**Comment by le-darshan** [comment]
actually i was showing the first name and last name for professionals in drop down but some has no entry in that fields that's why it was showing blank records but now the issue is fixed.
