### ISSUE TITLE
Deleted User, content not deleted

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#56]
Username SummerTree2 uploaded photos.
I logged in as admin and deleted that user and set attribute all content to TesterPro5 user.
Looking at the site, the photos uploaded by SummerTree2 are still there but with no user name.
When an account is deleted, the content such as the photos should be deleted or otherwise removed from the site also.

**Comment by Mark-Jefferson** [comment]
Please remove all content uploaded and created by a user when a user account is deleted.

**Comment by Mark-Jefferson** [comment]
whats the status on this?

**Comment by Mark-Jefferson** [comment]
I still need to know the status on this

**Comment by le-darshan** [comment]
sorry, i forgot to reply on this issue, now we are deleteing all the photos , projects and favorite books of user when the user is deleted.
