### ISSUE TITLE
User sees create article tabs on pro page

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#59]
I logged in as a normal user, window shopper, and visited a professional profile page. I was able to see the Live and Pending tabs for creating articles, and the title and body fields with all controls. 
Also when on the professional profile page, the Your WedWishes submenu changes to the Professional submenu options.

Originally the "Submit An Article", or Write a Blog Post, was supposed to be a link that was available to professionals on the admin area. And the front end was only supposed to show a list of articles they've published previously along with the published photos tab. 

Will it help you to change the tab for Articles to just a list of published articles?
And should we put a link to "Submit An Article" in the professional Your WedWishes Submenu under Your Projects, that will take them to create an article in the back end admin area?

Let me know if that sounds good or you have a better idea.

**Comment by le-darshan** [comment]
the sub menus issue is fixed now and for articles i liked the seccond one that list professional's artilces in front and give a menu to submit a new article that will redirect to admin. i have implemented it on dev can you test it.

**Comment by Mark-Jefferson** [comment]
There is an extra / in the url http://wedwishes.com/dev1/wp-admin//post-new.php on the navigation. Please remove it.
