### ISSUE TITLE
Users Removed, Pages not working

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#65]
All non admin users have been removed. Now these pages only work when logged in as Admin:
http://wedwishes.com/dev1/signin-page
http://wedwishes.com/dev1/browse-photos/
http://wedwishes.com/dev1/discuss-ideas/

Please investigate.

**Comment by le-darshan** [comment]
the pages was created by me so when you removed my account the pages were moved to trash. i have reset the pages with Administrator account now

**Comment by Mark-Jefferson** [comment]
ok. Pages that are functional, like signin and professional directory should not be tied to any user account. They need to be part of the child theme. Will you be able to do that?

**Comment by Mark-Jefferson** [comment]
I need an answer to the last question above.

**Comment by le-darshan** [comment]
the pages are in child theme but we can not access them directly. we have to create a page in admin panel and assign that page to your theme template. so indirectly it assigns the author of the page. but now we have created all the pages with admin user and admin will not be deleted so page also will not be deleted.
