### ISSUE TITLE
Can not upload profile pic for User account

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#73]
I have tested on more machines and still can not upload a profile pic in a user account and get the following error message
![image](https://cloud.githubusercontent.com/assets/9610332/5406574/4f2c61c4-8183-11e4-927e-2b881b33af16.png)

**Comment by Mark-Jefferson** [comment]
Now I am getting a Permissions error when I try to upload a profile image from the User login Edit profile page. "You don't have permission to upload files."

![image](https://cloud.githubusercontent.com/assets/9610332/5560372/174f91f6-8d52-11e4-9b9e-6edd791f212c.png)

**Comment by le-darshan** [comment]
this permission error is removed now user can update profile image
