### ISSUE TITLE
User Profile page discussions tab content

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#75]
The users should see a list of posts they've made in the discussion module. Please remove the Create A New Topic from the profile page discussion tab and replace with a list of only topics the user has commented on.
![image](https://cloud.githubusercontent.com/assets/9610332/5406653/877f5350-8184-11e4-82db-967c2cf74f15.png)

**Comment by le-darshan** [comment]
create new topic is removed. but i want to ask a question about this. i think this is the only place from where user can create discussion topic so do you want to place this add new topic section on any other place or page ?

**Comment by Mark-Jefferson** [comment]
The new topics are created in the discussion boards under Discuss ideas. This should only be a list of discussions related to the user. It should not contain any functionality such as reply or create new, just a link to the discussion they have commented on or created  on the Discuss Ideas board.
https://drive.google.com/file/d/0B8YmuQMr98J_dWREQVR1bDczUmc/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/9610332/5560350/7494ca9a-8d50-11e4-81bd-23dbd181c5bc.png)

---

Also I commented on a topic started by another user with Tester03 user account, and there is nothing listed in my profile page discussion tab on Tester03 profile.

**Comment by le-darshan** [comment]
this issue fixed now its showing only list of discussion on which user has comment or create on discussion board.
