### ISSUE TITLE
Add Share links and Question function to photos

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#76]
See the screenshot for details and refer to the photos on Houzz.com for reference
https://drive.google.com/file/d/0B8YmuQMr98J_TnNYQVBFZHJ2bjA/view?usp=sharing

Let me know if you have any doubts or questions.

**Comment by le-darshan** [comment]
the changes are done new question popup is implemented kindly suggest me if you need any extra field or want to change any field in the new popup
