### ISSUE TITLE
Professional Projects issues 1

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#77]
Refer to the screen shot for notes.
https://drive.google.com/file/d/0B8YmuQMr98J_WVJySTBiX1dQZVU/view?usp=sharing

**Comment by le-darshan** [comment]
title issue is fixed now and i have checked for the label of media i am not getting this issue now so can you check it.

**Comment by Mark-Jefferson** [comment]
Photos already uploaded are still not showing and this tab still has no name in it. 
Shouldn't this show my photos already uploaded and say Media Library? Let me know.

https://drive.google.com/file/d/0B8YmuQMr98J_d09TX1p3SUFmeDA/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/9610332/5560364/882b96fa-8d51-11e4-9d6f-e33d8267830e.png)

**Comment by le-darshan** [comment]
the media tab and photos are displaying now.
there was some filters placed for media upload in older code. i have commented now.
