### ISSUE TITLE
User Registration Step 1 blank page and URL

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#79]
I used the facebook button to register and was redirected to a blank page, it should have instructions and a link to browse photos, the url also needs to be changed.
See screen shot for more details
https://drive.google.com/file/d/0B8YmuQMr98J_QnRWRlJQQ1ZLclU/view?usp=sharing

**Comment by le-darshan** [comment]
this issue is fixed now and url is also changed
