### ISSUE TITLE
User question email from photo

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#80]
The email sent to professionals from user question needs some changes. Please review the screenshot comments and let me know if all this is possible.

See screen shot for details:
https://drive.google.com/file/d/0B8YmuQMr98J_QnRWRlJQQ1ZLclU/view?usp=sharing

**Comment by le-darshan** [comment]
i think this screenshot is not related to this point can you verify and provide the appropriate screenshot so that i can make changes.

**Comment by Mark-Jefferson** [comment]
Sorry, here is the correct link
https://drive.google.com/file/d/0B8YmuQMr98J_MnpxVWxQaGNTR00/view?usp=sharing

**Comment by le-darshan** [comment]
the changes of ask question mail is done
