### ISSUE TITLE
Photo Question Email form 1

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#81]
1. Please change the title on the form
2. Please add a text line above the first field
   See screen shot for details
   https://drive.google.com/file/d/0B8YmuQMr98J_SUVab2E0Mm9ZeDg/view?usp=sharing

Also when an email is sent using this form and I click on the Question link for a different photo, the "Email sent successfully" is remaining on the form before sending the second form. Please make sure that success message goes away when the form is closed or when a new form is opened.

**Comment by le-darshan** [comment]
the changes for the popup in ask question is done. and email success message issue is also fixed
