### ISSUE TITLE
Pro Contact Name is not displaying

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#83]
On professional profile page, Contact: should display First name Last name from their profile information. It is currently blank.
https://drive.google.com/file/d/0B8YmuQMr98J_dnJTZHo5M1ZSY1E/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/9610332/5560317/030b3b40-8d4e-11e4-88db-e6b9dc549eff.png)

**Comment by le-darshan** [comment]
contact info is displaying first name and last name in professional profile now.
