### ISSUE TITLE
Professional New Article link

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#85]
Under the Professional Profile page when logged in as professional, I thought we should have a Submit New Article link under the articles tab like the Project photos tab has? Yes?
![image](https://cloud.githubusercontent.com/assets/9610332/5560424/bf3e8508-8d56-11e4-9846-2369679ca618.png)

**Comment by le-darshan** [comment]
submit an article link is placed under the articles tab.
