### ISSUE TITLE
Favorites cover image

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#86]
Remove hard coded width and height from favorites images and add max width and height to css. See image for details.

![image](https://cloud.githubusercontent.com/assets/9610332/5560449/be1e8bf8-8d58-11e4-9835-d25fb4df2864.png)

**Comment by le-darshan** [comment]
hard coded height and width is removed and added to the stylesheet.

**Comment by Mark-Jefferson** [comment]
I am still seeing the hardcoded size in the code. Also the same problem is happening on the thumbnails inside the favorites book as well. Let me know if I'm missing something.

https://drive.google.com/file/d/0B8YmuQMr98J_RmhHLVBqTEJnOE0/view?usp=sharing

https://drive.google.com/file/d/0B8YmuQMr98J_VkFsS2tsWVBralU/view?usp=sharing

**Comment by le-darshan** [comment]
actually i updated in wedwishe.com by mistake sorry. but now i have reverted this change from wedwishes.com and implemented it on dev.
