### ISSUE TITLE
Cant edit image info in professional account

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#88]
I am not able to edit any of my uploaded image information when logged in as a professional in my media gallery.  see screenshot
https://drive.google.com/file/d/0B8YmuQMr98J_UXhBM25jTUxVQVU/view?usp=sharing

**Comment by le-darshan** [comment]
the user who uploads the image, he can only edit or add caption in his particular image only not in other user's uploaded image.
![media library wedwishes wordpress](https://cloud.githubusercontent.com/assets/5223025/5592074/5b47aacc-91d7-11e4-8579-cdb0a03047b1.png)
