### ISSUE TITLE
Professional Article was published without admin approval

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#89]
I created this article as a professional, and clicked the publish button. It is then supposed to be only submitted for admin approval for admin to publish, but it was published right away without approval. Please make sure the admin has to approve before publishing to live site.
http://wedwishes.com/dev1/beaded-dresses-coming-back/

**Comment by le-darshan** [comment]
i have fixed this issue now can you test it.
