### ISSUE TITLE
Menu item Your WedWishes missing

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#93]
The sign in menu link used to change to Your WedWishes when logged in, but now it is showing Logout instead. Please return it to the Your WedWishes with submenu when logged in.
I need this bug fixed before I can access the professional admin area to test other open tickets.

**Comment by le-darshan** [comment]
Please test

**Comment by Mark-Jefferson** [comment]
Menu fixed
