### ISSUE TITLE
Project manager add photos bug

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#98]
When logged in as a professional and create a new project in project manager, I am able to see all the photos uploaded by the administrator and not just the photos uploaded by my professional account.
It should be restricted to only photos uploaded by my professional account.
![image](https://cloud.githubusercontent.com/assets/9610332/6207927/0cdb72a0-b57d-11e4-8401-7fbb4fe3c9e7.png)

**Comment by le-darshan** [comment]
This issue is fixed.can you please test it?

**Comment by Mark-Jefferson** [comment]
Good job, fixed.
